name: Neural_Pulse
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  google_mlkit_face_detection: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true