name: neural_pulse
description: "Neural Pulse - AI Database Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  google_mlkit_face_detection: ^0.10.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/brain_icon.png"