name: neural_pulse
description: "Neural Pulse - AI Database Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  permission_handler: ^11.0.1
  cookie_jar: ^4.0.8
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  google_mlkit_face_detection: ^0.10.0  # Google ML Kit for face detection
  crypto: ^3.0.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  google_mlkit_face_detection: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/brain_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/brain_icon.png"